### ISSUE TITLE
iOS Message / Unity view enabled as default

### ISSUE THREAD

**Issue by vpsantos** [f111fei/react-native-unity-demo#10]
I am able to run the demo, that is working fine on Android, but on iOS the message isn't received from Unity. Am I missing something?

I also would like to have the Unity view starting already enabled instead of clicking on "Toggle Unity", but just changing the state.renderUnity to true doesn't work.

Any idea?
My Unity version is 2017.4.0f1 and React Native is 0.53.0.

Thanks!

**Comment by f111fei** [comment]
https://github.com/f111fei/react-native-unity-view/commit/075ea3d1e01497b43b32de2c1a597936098d3e19

Try update `react-native-unity-view`  to 1.1.2 ?
