### ISSUE TITLE
missing Bulk_Generices_5.cpp

### ISSUE THREAD

**Issue by vikas5914** [f111fei/react-native-unity-demo#2]
I just tried this demo. I am using Unity 2017.2.0f3 and Xcode 9.3.

![screen shot 2018-04-09 at 1 52 28 am](https://user-images.githubusercontent.com/7912297/38488581-8fdb76ba-3c01-11e8-9a18-3e379bc8c6eb.png)

**Comment by f111fei** [comment]
Try remove UnityExport folder reference in Xcode and Build => Export IOS again.

**Comment by vikas5914** [comment]
Thanks. it worked.

**Comment by vikas5914** [comment]
One question. did you tried this with Unity ARKit?

**Comment by f111fei** [comment]
No!!! ARKit may be need other settings. I had use it in our Vuforia project.
