### ISSUE TITLE
error: Build input file cannot be found: Bulk_UnityEngine.UnityConnectModule_0.cpp

### ISSUE THREAD

**Issue by omer-halici** [f111fei/react-native-unity-demo#20]
Hi,
I am trying to build this demo on my mac which has unity 2018.2.11f1 and xcode version 10.0. I am getting the following error:

error: Build input file cannot be found: '/Users/myUser/Desktop/react-native-unity-demo-master/ios/UnityExport/Classes/Native/Bulk_UnityEngine.UnityConnectModule_0.cpp'

Any ideas?

**Comment by omer-halici** [comment]
I don't remember how but it is fixed. Maybe I did the similar things. Thank you anyway!

**Comment by amit00978** [comment]
@chchwy @omer-halici Bro I am facing the same problem and stuck on this point from the last 2 days any help highly appreciated.
