### ISSUE TITLE
IOS error /Users/xzper/workspace/web/npm-package/react-native/unity/demo/ios/UnityExport/Data doesn't exist

### ISSUE THREAD

**Issue by iSamity** [f111fei/react-native-unity-demo#25]
When building the error "/Users/xzper/workspace/web/npm-package/react-native/unity/demo/ios/UnityExport/Data" occurs from the master.

This is probably a wrong link because I am not xzper. However can't find the file that is linking to it. 
Does somebody have the solution

**Comment by iSamity** [comment]
solved, remove in build phase --> copy bundle resource the specific file

**Comment by ham118** [comment]
> solved, remove in build phase --> copy bundle resource the specific file

Disappeared this error after following this step 👍
