### ISSUE TITLE
why run app defualt show untiy view

### ISSUE THREAD

**Issue by techistoner** [f111fei/react-native-unity-demo#26]
i use     "react-native": "0.57.3",
    "react-native-unity-view": "^1.1.6",
my first view is an rn view,but when i run the src by xcode ,show the untiy view by default,can not reach my other rn view.

**Comment by davegauch-vamp** [comment]
I am experiencing the same problem, when I run from xcode just unity without the RN UI.

**Comment by techistoner** [comment]
> I am experiencing the same problem, when I run from xcode just unity without the RN UI.

I haven't find out the reason，but i suspect this is caused by the memory issue.

**Comment by f111fei** [comment]
Duplicate https://github.com/f111fei/react-native-unity-view/issues/70
