### ISSUE TITLE
Could not find method bundle() for arguments 

### ISSUE THREAD

**Issue by SausCode** [f111fei/react-native-unity-demo#29]
Getting this issue, not really sure why as bundle is in my build.gradle
* Where:                                                                                                                               Build file 'C:\Users\****\Documents\GitHub\react-native-unity-demo\android\UnityExport\build.gradle' line: 78                                                                                                                                                                * What went wrong:                                                                                                                     A problem occurred evaluating project ':UnityExport'.                                                                                  > Could not find method bundle() for arguments [build_2nxm6hxyy0df3z06p7r6bwen4$_run_closure3$_closure12@1ad6f36] on object of type co m.android.build.gradle.LibraryExtension.
--

**Comment by xchesh** [comment]
I have same issue

**Comment by SilvanBauser** [comment]
same here

**Comment by SausCode** [comment]
I figured out a solution that worked for me.

In the offending build.gradle remove the lines at the end with bundle.

**Comment by andorfermichael** [comment]
I get the same error. If I remove the bundle section I get another error:

```
* What went wrong:
A problem occurred configuring project ':UnityExport'.
> java.lang.NullPointerException (no error message)
```
