### ISSUE TITLE
Faild ":CFBundleIdentifier" Doesn't Exist

### ISSUE THREAD

**Issue by dekemega** [f111fei/react-native-unity-demo#3]
it failed with this error
![error](https://user-images.githubusercontent.com/23610404/38776874-dc5e842e-40a6-11e8-98bb-6b79324f57d9.jpg)
using Unity 5.6.1f1
i tried it several times with no success ... can you please give it a try

**Comment by f111fei** [comment]
Do not support emulator.  And it is better to upgrade Unity to 2017.2.0f3

**Comment by dekemega** [comment]
you're right .. i am using emulator right now 
i'll try it on real device soon 
Thank you very much
