### ISSUE TITLE
npm run ios results in CFBundleIdentifier, Does Not Exist, cant run from xcode on device

### ISSUE THREAD

**Issue by AmitShah** [f111fei/react-native-unity-demo#7]
when running :

npm run ios

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/rnunitydemo.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

when running same project from xcode:

"_GetAppController", referenced from:
      +[RNUnityViewManager handleAppStateDidChange:] in libRNUnityView.a(RNUnityViewManager.o)
      -[RNUnityViewManager setBridge:] in libRNUnityView.a(RNUnityViewManager.o)
      -[RNUnityView initWithFrame:] in libRNUnityView.a(RNUnityView.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by f111fei** [comment]
duplicate https://github.com/f111fei/react-native-unity-demo/issues/5
